In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)


Original Array: [1 2 3 4 5]
Reversed Array: [1 2 3 4 5]


In [15]:
import numpy as np 
arr=np.array([[1,2,3],[2,3,4],[1,2,3]])
#method1
flat=arr.flatten()
print(flat)
#method2
flat2=arr.ravel()
print(flat2)

[1 2 3 2 3 4 1 2 3]
[1 2 3 2 3 4 1 2 3]


In [23]:
import numpy as np 
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
#method1
np.array_equal(arr1,arr2)
#mehtod2
np.allclose(arr1,arr2)

True

In [32]:
import numpy as np 
arr=np.array([1,2,3,4,5,2,1,1,1])
values,counts=np.unique(arr1,return_counts=True)
most_frequent=values[np.argmax(counts)]
indices=np.where(arr==most_frequent)[0]
print(most_frequent)
print(indices)

1
[0 6 7 8]


In [41]:
import numpy as np 
arr=np.array([1,1,1,2,3,4,2,4,3,3,3])
values,counts=np.unique(arr1,return_counts=True)
most_frequent=values[np.argmax(counts)]
indices=np.where(arr==most_frequent)[0]
print(most_frequent)
print(indices)

1
[0 1 2]


In [6]:
import numpy as np 
gfg=np.matrix('[4,1,9;1,2,3;4,5,6]')
total=gfg.sum()
total_rows=gfg.sum(axis=1)
total_cols=gfg.sum(axis=0)
#i)
print(total)
#ii)
print(total_rows)
#iii)
print(total_cols)

35
[[14]
 [ 6]
 [15]]
[[ 9  8 18]]


In [8]:
import numpy as np 
arr=np.array([[55,25,15],[30,44,2],[11,45,77]])
diag_sum=np.trace(arr)
eigenvalues,eigenvectors=np.linalg.eig(arr)
determinant=np.linalg.det(arr)
print(diag_sum)
print(eigenvalues)
print(eigenvectors)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
137180.0000000001


In [14]:
import numpy as np 
p1=np.array([[1,2],[2,3]])
p2=np.array([[4,5],[6,7]])
product=np.dot(p1,p2)
cov1=np.cov(p1.T)
cov2=np.cov(p2.T)
print(product)
print(cov1)
print(cov2)


[[16 19]
 [26 31]]
[[0.5 0.5]
 [0.5 0.5]]
[[2. 2.]
 [2. 2.]]


In [16]:
import numpy as np 
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
inner=np.inner(x,y)
outer=np.outer(x,y)
cartesian=np.array(np.meshgrid(x.flatten(),y.flatten())).T.reshape(-1,2)
print(inner)
print(outer)
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [39]:
import numpy as np 
arr=np.array([[1,2,-3],[-4,5,6]])
#i
abs_arr=np.abs(arr)
print(abs_arr)
#ii
flat=arr.flatten()
print(flat)
p_25=np.percentile(flat,25)
print("25th percentile is",p_25)
p_50=np.percentile(flat,50)
print("50th percentile is",p_50)
p_75=np.percentile(flat,75)
print("75th percentile is",p_75)
p_25col=np.percentile(arr,25,axis=0)
p_50col=np.percentile(arr,50,axis=0)
p_75col=np.percentile(arr,75,axis=0)
print("percentiles by collumn are",p_25,p_50,p_75)
p_25row=np.percentile(arr,25,axis=1)
p_50row=np.percentile(arr,50,axis=1)
p_75row=np.percentile(arr,75,axis=1)
print(p_25,p_50,p_75)


[[1 2 3]
 [4 5 6]]
[ 1  2 -3 -4  5  6]
25th percentile is -2.0
50th percentile is 1.5
75th percentile is 4.25
percentiles by collumn are -2.0 1.5 4.25
-2.0 1.5 4.25


In [49]:
import numpy as np 
arr=np.array([[1,-2,-3],[-4,5,6]])
mean_flat = np.mean(arr)   
med_flat = np.median(arr) 
std_flat = np.std(arr)     
print(mean_flat)
print(med_flat)
print(std_flat)
#for collumns
med_col=np.median(arr,axis=0)
mean_col=np.mean(arr,axis=0)
std_col=np.std(arr,axis=0)
print(med_col)
print(mean_col)
print(std_col)
#for rows
med_row=np.median(arr,axis=1)
mean_row=np.mean(arr,axis=1)
std_row=np.std(arr,axis=1)
print(med_row)
print(mean_row)
print(std_row)

0.5
-0.5
3.8622100754188224
[-1.5  1.5  1.5]
[-1.5  1.5  1.5]
[2.5 3.5 4.5]
[-2.  5.]
[-1.33333333  2.33333333]
[1.69967317 4.49691252]


In [55]:
import numpy as np 
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
floor=np.floor(a)
ceil=np.ceil(a)
truncate=np.trunc(a)
round=np.round(a)
print(floor)
print(ceil)
print(truncate)
print(round)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [59]:
#ques 3 
#a)
import numpy as np 
a=np.array([10,52,62,16,16,54,453])
#i)
sorted=np.sort(a)
print(a)
#ii)
indices=np.argsort(a)
print(indices)
#iii)
lowest4=np.sort(a)[ :4]
print(lowest4)
#iv)
highest5=np.sort(a)[-5: ]
print(highest5)

[ 10  52  62  16  16  54 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [93]:
import numpy as np

a = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = a[a == np.floor(a)]
print( int_elements)
float=a[a!=np.floor(a)]
print(float)


[1. 2. 3. 2.]
[1.2 2.2]
